# Generated by Django 2.2.9 on 2020-04-21 22:03

import django.db.models.deletion
from django.db import migrations
from django.db import models


def set_site_to_app_config(apps, schema_editor):

    NewsBlogConfig = apps.get_model('aldryn_newsblog', 'NewsBlogConfig')
    Page = apps.get_model('cms', 'Page')
    for app_config in NewsBlogConfig.objects.all():
        pages = Page.objects.filter(application_namespace=app_config.namespace)
        if pages.exists():
            app_config.site = pages.first().node.site
            app_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('aldryn_newsblog', '0016_auto_20180329_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.RunPython(set_site_to_app_config),
    ]
