# Generated by Django 2.2.9 on 2020-08-11 23:04

import aldryn_newsblog.fields
import aldryn_newsblog.fields
import aldryn_translation_tools.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations
from django.db import models
from django.utils import translation

translation.activate(settings.LANGUAGE_CODE)


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0018_auto_20200526_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('newsblog_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aldryn_newsblog.NewsBlogConfig')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=(aldryn_translation_tools.models.TranslatedAutoSlugifyMixin, aldryn_translation_tools.models.TranslationHelperMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Provide a “slug” or leave blank for an automatically generated one.', max_length=255, verbose_name='slug')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.Category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'aldryn_newsblog_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'slug'), ('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='article',
            name='new_categories',
            field=aldryn_newsblog.fields.CategoryManyToManyField(blank=True, to='aldryn_newsblog.Category', verbose_name='categories'),
        ),
    ]
