# Generated by Django 2.2.9 on 2020-05-22 21:38

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aldryn_newsblog', '0018_auto_20200520_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='placeholder_feature',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aldryn_newsblog_feature', slotname='newsblog_feature', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='newsblogconfig',
            name='placeholder_sidebar',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aldryn_newsblog_sidebar', slotname='newsblog_sidebar', to='cms.Placeholder'),
        ),
    ]
