# Generated by Django 2.2.9 on 2020-08-11 23:04

import aldryn_newsblog.fields
import aldryn_newsblog.fields
import aldryn_translation_tools.models
import django.db.models.deletion
import parler.fields
import parler.models
from aldryn_categories.models import Category as OldCategory
from aldryn_newsblog.models import Article
from aldryn_newsblog.models import Category as NewCategory
from aldryn_newsblog.cms_appconfig import NewsBlogConfig
from django.conf import settings
from django.db import migrations
from django.db import models
from django.utils import translation

translation.activate(settings.LANGUAGE_CODE)


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0021_migrate_aldryn_categories_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='new_categories',
            new_name='categories',
        ),
    ]
