# Generated by Django 2.2.17 on 2021-04-21 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_newsblog', '0024_auto_20210203_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Only used if AUTHOR is not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aldryn_people.Person', verbose_name='Author (Django CMS User)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='aldryn_newsblog.Category', verbose_name='categories'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Used in the URL. If changed, the URL will change. Clear it to have it re-created automatically.', max_length=255, verbose_name='slug')),
                ('function', models.CharField(blank=True, default='', max_length=255)),
                ('app_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aldryn_newsblog.NewsBlogConfig', verbose_name='Apphook configuration')),
                ('visual', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_override', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'unique_together': {('slug', 'app_config')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aldryn_newsblog.Author', verbose_name='author'),
        ),
    ]
