# Generated by Django 2.2.28 on 2022-11-11 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aldryn_newsblog', '0027_taggit_tags_to_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
